# Project: Project3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = vd2/main.o
LINKOBJ  = vd2/main.o
LIBS     = -L"D:/IT FPT/SEM1/Dev-Cpp/MinGW64/lib" -L"D:/IT FPT/SEM1/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/IT FPT/SEM1/Dev-Cpp/MinGW64/include" -I"D:/IT FPT/SEM1/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/IT FPT/SEM1/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/IT FPT/SEM1/Dev-Cpp/MinGW64/include" -I"D:/IT FPT/SEM1/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/IT FPT/SEM1/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/IT FPT/SEM1/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Vd2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

vd2/main.o: vd2/main.c
	$(CC) -c vd2/main.c -o vd2/main.o $(CFLAGS)
