# Project: vd5
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "vd\ 5.o"
LINKOBJ  = "vd 5.o"
LIBS     = -L"D:/IT FPT/SEM1/Dev-Cpp/MinGW64/lib" -L"D:/IT FPT/SEM1/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/IT FPT/SEM1/Dev-Cpp/MinGW64/include" -I"D:/IT FPT/SEM1/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/IT FPT/SEM1/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/IT FPT/SEM1/Dev-Cpp/MinGW64/include" -I"D:/IT FPT/SEM1/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/IT FPT/SEM1/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/IT FPT/SEM1/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = vd5.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

"vd\ 5.o": vd\ 5.c
	$(CC) -c "vd 5.c" -o "vd 5.o" $(CFLAGS)
